 DATE:23.8.22          FRAUD PREDICTION-RADONDOM FOREST CLASSIFIER

In [1]:
#IMPORTING LIBRARIES
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import colorama
from colorama import Fore

In [2]:
#LOAD DATASET
dataset=pd.read_csv('fraud.csv')

In [3]:
#.head() displays first 5 samples of the dataset
dataset.head()

step     type    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1  PAYMENT   9839.64       170136.0       160296.36             0.0   
1     1  PAYMENT   1864.28        21249.0        19384.72             0.0   
2     1  PAYMENT  11668.14        41554.0        29885.86             0.0   
3     1  PAYMENT   7817.71        53860.0        46042.29             0.0   
4     1  PAYMENT   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  
0             0.0        0               0  
1             0.0        0               0  
2             0.0        0               0  
3             0.0        0               0  
4             0.0        0               0

In [4]:
#.value_counts() function returns a series containing counts of unique values
dataset["type"].value_counts()


CASH_OUT    5108
TRANSFER    4808
PAYMENT     4530
CASH_IN     1660
DEBIT        320
Name: type, dtype: int64

In [5]:
#CHECKING BALANCED DATA OR NOT
dataset["isFraud"].value_counts()

0    8213
1    8213
Name: isFraud, dtype: int64

#Here our class0 and class 1 are splited equally ie Balanced

In [6]:
#CHANGING STRING COLUMN ITO BINARY USING get_dummies
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1  11668.14        41554.0        29885.86             0.0   
3     1   7817.71        53860.0        46042.29             0.0   
4     1   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
0             0.0        0               0              0           0   
1             0.0        0               0              0           0   
2             0.0        0               0              0           0   
3             0.0        0               0              0           0   
4             0.0        0               0              0           0   

   type_PAYMENT  type_TRANSFER  
0             1              0  
1             1              0  
2             1              0  
3             1              0  
4             1              0

In [8]:
#ASSIGNING INPUT AND OUTPUT
indep=dataset.drop(["isFraud"],axis=1)

In [9]:
indep.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1  11668.14        41554.0        29885.86             0.0   
3     1   7817.71        53860.0        46042.29             0.0   
4     1   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFlaggedFraud  type_CASH_OUT  type_DEBIT  type_PAYMENT  \
0             0.0               0              0           0             1   
1             0.0               0              0           0             1   
2             0.0               0              0           0             1   
3             0.0               0              0           0             1   
4             0.0               0              0           0             1   

   type_TRANSFER  
0              0  
1              0  
2              0  
3              0  
4              0

In [10]:
#ASSIGNING OUPUT
dep=dataset["isFraud"]
dep.head()

0    0
1    0
2    0
3    0
4    0
Name: isFraud, dtype: int64

In [11]:
#SPLITING TRAINING AND TEST SET DATA
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0,stratify=dep)


In [12]:
#SAMPLE OF  INPUT DATA FROM ORIGINAL DATASET
x_train.head()

step       amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
3367      2     11493.01           0.00            0.00            0.00   
15644   674  10000000.00    16250438.78      6250438.78            0.00   
14935   610    646676.42      646676.42            0.00       111156.33   
8442     19   1861008.32     1861008.32            0.00            0.00   
4599      4      4083.67       69086.00        65002.33            0.00   

       newbalanceDest  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
3367             0.00               0              0           0   
15644            0.00               0              0           0   
14935       757832.75               0              1           0   
8442             0.00               0              0           0   
4599             0.00               0              0           0   

       type_PAYMENT  type_TRANSFER  
3367              1              0  
15644             0              1  
14935             0              0  
8442              0              1  
4599              1              0

In [13]:
# 1.RANDOM_CLASSIFIER USING GRIDSEARCH
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entrophy'],
            'max_features':['auto','sqrt','log2'],
            'n_estimators':[10,100]}
randomgrid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1')
randomgrid.fit(x_train,y_train)

print(randomgrid.best_params_)


Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\ensemble\_forest.py", line 467, in fit
    for i, t in enumerate(trees)
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\joblib\parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:

{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}


In [14]:
#SAMPLE OF DATA FROM ORIGINAL DATASET
y_pred=randomgrid.predict(x_test)


In [15]:
y_pred


array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [16]:
#EVALUTION METRICS IN CLASSIFICATION
from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(y_pred,y_test)
print( Fore.BLUE+"Random forest Confusion matrix:")
print(cm1)

Random forest Confusion matrix:
[[2738   10]
 [   0 2728]]


In [17]:
#CLASSIFICATION REPORT
from sklearn.metrics import classification_report
clf1=classification_report(y_pred,y_test)
print(Fore.RED + "Random forest:")
print(clf1)
print(cm1)

Random forest:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2748
           1       1.00      1.00      1.00      2728

    accuracy                           1.00      5476
   macro avg       1.00      1.00      1.00      5476
weighted avg       1.00      1.00      1.00      5476

[[2738   10]
 [   0 2728]]


In [18]:
import pickle
filename="final_RandomForest_Classifier"
pickle.dump(randomgrid,open(filename,'wb'))

In [19]:
load_model_randomforest = pickle.load(open(filename,'rb'))

In [21]:
load_model_randomforest.predict([[1,93456,45,576,232,43,34,4,2,2,9]])

C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0], dtype=int64)