 DATE:23.8.22          FRAUD PREDICTION-DECISION TREE CLASSIFICATION

In [8]:
#IMPORTING LIBRARIES
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import colorama
from colorama import Fore

In [9]:
#LOAD DATASET
dataset=pd.read_csv('fraud.csv')


In [10]:
dataset.head()

step     type    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1  PAYMENT   9839.64       170136.0       160296.36             0.0   
1     1  PAYMENT   1864.28        21249.0        19384.72             0.0   
2     1  PAYMENT  11668.14        41554.0        29885.86             0.0   
3     1  PAYMENT   7817.71        53860.0        46042.29             0.0   
4     1  PAYMENT   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  
0             0.0        0               0  
1             0.0        0               0  
2             0.0        0               0  
3             0.0        0               0  
4             0.0        0               0

In [11]:
dataset["type"].value_counts()


CASH_OUT    5108
TRANSFER    4808
PAYMENT     4530
CASH_IN     1660
DEBIT        320
Name: type, dtype: int64

In [12]:
#CHECKING BALANCED DATA OR NOT
dataset["isFraud"].value_counts()

0    8213
1    8213
Name: isFraud, dtype: int64

In [13]:
#CHANGING STRING COLUMN ITO BINARY USING get_dummies
dataset=pd.get_dummies(dataset,drop_first=True)

In [14]:
dataset.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1  11668.14        41554.0        29885.86             0.0   
3     1   7817.71        53860.0        46042.29             0.0   
4     1   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
0             0.0        0               0              0           0   
1             0.0        0               0              0           0   
2             0.0        0               0              0           0   
3             0.0        0               0              0           0   
4             0.0        0               0              0           0   

   type_PAYMENT  type_TRANSFER  
0             1              0  
1             1              0  
2             1              0  
3             1              0  
4             1              0

In [15]:
#ASSIGNING INPUT AND OUTPUT
indep=dataset.drop(["isFraud"],axis=1)

In [16]:
indep.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1  11668.14        41554.0        29885.86             0.0   
3     1   7817.71        53860.0        46042.29             0.0   
4     1   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFlaggedFraud  type_CASH_OUT  type_DEBIT  type_PAYMENT  \
0             0.0               0              0           0             1   
1             0.0               0              0           0             1   
2             0.0               0              0           0             1   
3             0.0               0              0           0             1   
4             0.0               0              0           0             1   

   type_TRANSFER  
0              0  
1              0  
2              0  
3              0  
4              0

In [17]:
#ASSIGNING OUPUT
dep=dataset["isFraud"]
dep.head()

0    0
1    0
2    0
3    0
4    0
Name: isFraud, dtype: int64

In [18]:
#SPLITING TRAINING AND TEST SET DATA
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)


In [19]:
#SAMPLE OF  INPUT DATA FROM ORIGINAL DATASET
x_train.head()

step      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
14402   561  2763025.35     2763025.35             0.0            0.00   
11624   302   633384.46      633384.46             0.0            0.00   
6422      6     9396.00      936212.00        926816.0            0.00   
9427    103   710385.55      710385.55             0.0            0.00   
5126      5    59691.76           0.00             0.0      4254247.97   

       newbalanceDest  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
14402            0.00               0              0           0   
11624            0.00               0              0           0   
6422             0.00               0              0           0   
9427             0.00               0              0           0   
5126       4313939.72               0              0           0   

       type_PAYMENT  type_TRANSFER  
14402             0              1  
11624             0              1  
6422              1              0  
9427              0              1  
5126              0              1

#2.DECISION TREE CLASSIFICATION

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entrophy'],
            'max_features':['auto','sqrt','log2'],
            'splitter':['best','random']}
decision_grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
decision_grid.fit(x_train,y_train)

print(decision_grid.best_params_)


Fitting 5 folds for each of 12 candidates, totalling 60 fits
{'criterion': 'gini', 'max_features': 'log2', 'splitter': 'best'}


C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: '

In [27]:
y_pred=decision_grid.predict(x_test)
y_pred

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [28]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred1,y_test)
print("Decisiontree confusion matrix:")
print(cm)

Decisiontree confusion matrix:
[[2711   10]
 [  11 2744]]


In [29]:
from sklearn.metrics import classification_report
clf=classification_report(y_pred1,y_test)
print("Decisiontree:")
print(clf)
print(cm)

Decisiontree:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2721
           1       1.00      1.00      1.00      2755

    accuracy                           1.00      5476
   macro avg       1.00      1.00      1.00      5476
weighted avg       1.00      1.00      1.00      5476

[[2711   10]
 [  11 2744]]


In [30]:
#model store
import pickle
filename='DecisionTree_Classifier.sav'
pickle.dump(decision_grid,open(filename,'wb'))



In [31]:
load_model_decision_tree=pickle.load(open(filename,'rb'))

In [33]:
load_model_decision_tree.predict([[1,93456,45,576,232,43,34,4,2,2,9]])

C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1], dtype=int64)