In [ ]:
 DATE:23.8.22          FRAUD PREDICTION-SUPPORT VECTOR MAACHINE

In [1]:
#IMPORTING LIBRARIES
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import colorama
from colorama import Fore

In [2]:
#LOAD DATASET
dataset=pd.read_csv('fraud.csv')
dataset.head()

step     type    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1  PAYMENT   9839.64       170136.0       160296.36             0.0   
1     1  PAYMENT   1864.28        21249.0        19384.72             0.0   
2     1  PAYMENT  11668.14        41554.0        29885.86             0.0   
3     1  PAYMENT   7817.71        53860.0        46042.29             0.0   
4     1  PAYMENT   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  
0             0.0        0               0  
1             0.0        0               0  
2             0.0        0               0  
3             0.0        0               0  
4             0.0        0               0

In [3]:
dataset["type"].value_counts()


CASH_OUT    5108
TRANSFER    4808
PAYMENT     4530
CASH_IN     1660
DEBIT        320
Name: type, dtype: int64

In [4]:
#CHECKING BALANCED DATA OR NOT
dataset["isFraud"].value_counts()

0    8213
1    8213
Name: isFraud, dtype: int64

In [5]:
#CHANGING STRING COLUMN ITO BINARY USING get_dummies
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1  11668.14        41554.0        29885.86             0.0   
3     1   7817.71        53860.0        46042.29             0.0   
4     1   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
0             0.0        0               0              0           0   
1             0.0        0               0              0           0   
2             0.0        0               0              0           0   
3             0.0        0               0              0           0   
4             0.0        0               0              0           0   

   type_PAYMENT  type_TRANSFER  
0             1              0  
1             1              0  
2             1              0  
3             1              0  
4             1              0

In [7]:
#ASSIGNING INPUT AND OUTPUT
indep=dataset.drop(["isFraud"],axis=1)

In [8]:
indep.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1  11668.14        41554.0        29885.86             0.0   
3     1   7817.71        53860.0        46042.29             0.0   
4     1   7107.77       183195.0       176087.23             0.0   

   newbalanceDest  isFlaggedFraud  type_CASH_OUT  type_DEBIT  type_PAYMENT  \
0             0.0               0              0           0             1   
1             0.0               0              0           0             1   
2             0.0               0              0           0             1   
3             0.0               0              0           0             1   
4             0.0               0              0           0             1   

   type_TRANSFER  
0              0  
1              0  
2              0  
3              0  
4              0

In [9]:
#ASSIGNING OUPUT
dep=dataset["isFraud"]
dep.head()

0    0
1    0
2    0
3    0
4    0
Name: isFraud, dtype: int64

In [10]:
#SPLITING TRAINING AND TEST SET DATA
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0,stratify=dep)


In [11]:
#SAMPLE OF  INPUT DATA FROM ORIGINAL DATASET
x_train.head()

step       amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
3367      2     11493.01           0.00            0.00            0.00   
15644   674  10000000.00    16250438.78      6250438.78            0.00   
14935   610    646676.42      646676.42            0.00       111156.33   
8442     19   1861008.32     1861008.32            0.00            0.00   
4599      4      4083.67       69086.00        65002.33            0.00   

       newbalanceDest  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
3367             0.00               0              0           0   
15644            0.00               0              0           0   
14935       757832.75               0              1           0   
8442             0.00               0              0           0   
4599             0.00               0              0           0   

       type_PAYMENT  type_TRANSFER  
3367              1              0  
15644             0              1  
14935             0              0  
8442              0              1  
4599              1              0

In [12]:
#IMPORT SUPPORTVECTOR MODEL FROM SKLEARN
from sklearn.svm import SVC
svm=SVC()
svm.fit(x_train,y_train)


SVC()

In [13]:
y_pred=svm.predict(x_test)

In [14]:
y_pred

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_test)
print("svm confusion matrix:")
print(cm)

svm confusion matrix:
[[2685  766]
 [  53 1972]]


In [16]:
from sklearn.metrics import classification_report
clf=classification_report(y_pred,y_test)
print("svm classification report:")
print(clf)

svm classification report:
              precision    recall  f1-score   support

           0       0.98      0.78      0.87      3451
           1       0.72      0.97      0.83      2025

    accuracy                           0.85      5476
   macro avg       0.85      0.88      0.85      5476
weighted avg       0.88      0.85      0.85      5476



In [18]:
#save model
import pickle 
filename="svm.sav"
pickle.dump(svm,open(filename,'wb'))

In [19]:
#load model
load_model_svm=pickle.load(open(filename,'rb'))

In [21]:
load_model_svm.predict([[1,93456,45,576,232,43,34,4,2,2,9]])

C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


array([0], dtype=int64)