In [ ]:
 DATE:23.8.22          FRAUD PREDICTION

In [1]:
#IMPORTING LIBRARIES
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import colorama
from colorama import Fore

In [2]:
#LOAD DATASET
dataset=pd.read_csv('fraud.csv')
dataset

step      type      amount  oldbalanceOrg  newbalanceOrig  \
0         1   PAYMENT     9839.64      170136.00       160296.36   
1         1   PAYMENT     1864.28       21249.00        19384.72   
2         1   PAYMENT    11668.14       41554.00        29885.86   
3         1   PAYMENT     7817.71       53860.00        46042.29   
4         1   PAYMENT     7107.77      183195.00       176087.23   
...     ...       ...         ...            ...             ...   
16421   743  CASH_OUT   339682.13      339682.13            0.00   
16422   743  TRANSFER  6311409.28     6311409.28            0.00   
16423   743  CASH_OUT  6311409.28     6311409.28            0.00   
16424   743  TRANSFER   850002.52      850002.52            0.00   
16425   743  CASH_OUT   850002.52      850002.52            0.00   

       oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0                0.00            0.00        0               0  
1                0.00            0.00        0               0  
2                0.00            0.00        0               0  
3                0.00            0.00        0               0  
4                0.00            0.00        0               0  
...               ...             ...      ...             ...  
16421            0.00       339682.13        1               0  
16422            0.00            0.00        1               0  
16423        68488.84      6379898.11        1               0  
16424            0.00            0.00        1               0  
16425      6510099.11      7360101.63        1               0  

[16426 rows x 9 columns]

In [3]:
dataset["type"].value_counts()


CASH_OUT    5108
TRANSFER    4808
PAYMENT     4530
CASH_IN     1660
DEBIT        320
Name: type, dtype: int64

In [4]:
#CHECKING BALANCED DATA OR NOT
dataset["isFraud"].value_counts()

0    8213
1    8213
Name: isFraud, dtype: int64

In [5]:
#CHANGING STRING COLUMN ITO BINARY USING get_dummies
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

step      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0         1     9839.64      170136.00       160296.36            0.00   
1         1     1864.28       21249.00        19384.72            0.00   
2         1    11668.14       41554.00        29885.86            0.00   
3         1     7817.71       53860.00        46042.29            0.00   
4         1     7107.77      183195.00       176087.23            0.00   
...     ...         ...            ...             ...             ...   
16421   743   339682.13      339682.13            0.00            0.00   
16422   743  6311409.28     6311409.28            0.00            0.00   
16423   743  6311409.28     6311409.28            0.00        68488.84   
16424   743   850002.52      850002.52            0.00            0.00   
16425   743   850002.52      850002.52            0.00      6510099.11   

       newbalanceDest  isFraud  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
0                0.00        0               0              0           0   
1                0.00        0               0              0           0   
2                0.00        0               0              0           0   
3                0.00        0               0              0           0   
4                0.00        0               0              0           0   
...               ...      ...             ...            ...         ...   
16421       339682.13        1               0              1           0   
16422            0.00        1               0              0           0   
16423      6379898.11        1               0              1           0   
16424            0.00        1               0              0           0   
16425      7360101.63        1               0              1           0   

       type_PAYMENT  type_TRANSFER  
0                 1              0  
1                 1              0  
2                 1              0  
3                 1              0  
4                 1              0  
...             ...            ...  
16421             0              0  
16422             0              1  
16423             0              0  
16424             0              1  
16425             0              0  

[16426 rows x 12 columns]

In [7]:
#ASSIGNING INPUT AND OUTPUT
indep=dataset.drop(["isFraud"],axis=1)

In [8]:
indep

step      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0         1     9839.64      170136.00       160296.36            0.00   
1         1     1864.28       21249.00        19384.72            0.00   
2         1    11668.14       41554.00        29885.86            0.00   
3         1     7817.71       53860.00        46042.29            0.00   
4         1     7107.77      183195.00       176087.23            0.00   
...     ...         ...            ...             ...             ...   
16421   743   339682.13      339682.13            0.00            0.00   
16422   743  6311409.28     6311409.28            0.00            0.00   
16423   743  6311409.28     6311409.28            0.00        68488.84   
16424   743   850002.52      850002.52            0.00            0.00   
16425   743   850002.52      850002.52            0.00      6510099.11   

       newbalanceDest  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
0                0.00               0              0           0   
1                0.00               0              0           0   
2                0.00               0              0           0   
3                0.00               0              0           0   
4                0.00               0              0           0   
...               ...             ...            ...         ...   
16421       339682.13               0              1           0   
16422            0.00               0              0           0   
16423      6379898.11               0              1           0   
16424            0.00               0              0           0   
16425      7360101.63               0              1           0   

       type_PAYMENT  type_TRANSFER  
0                 1              0  
1                 1              0  
2                 1              0  
3                 1              0  
4                 1              0  
...             ...            ...  
16421             0              0  
16422             0              1  
16423             0              0  
16424             0              1  
16425             0              0  

[16426 rows x 11 columns]

In [9]:
#ASSIGNING OUPUT
dep=dataset["isFraud"]
dep

0        0
1        0
2        0
3        0
4        0
        ..
16421    1
16422    1
16423    1
16424    1
16425    1
Name: isFraud, Length: 16426, dtype: int64

In [10]:
#SPLITING TRAINING AND TEST SET DATA
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)


In [11]:
#SAMPLE OF  INPUT DATA FROM ORIGINAL DATASET
x_train

step       amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
14402   561   2763025.35     2763025.35            0.00            0.00   
11624   302    633384.46      633384.46            0.00            0.00   
6422      6      9396.00      936212.00       926816.00            0.00   
9427    103    710385.55      710385.55            0.00            0.00   
5126      5     59691.76           0.00            0.00      4254247.97   
...     ...          ...            ...             ...             ...   
9225     84    152331.26      152331.26            0.00            0.00   
13123   438   4626269.69     4626269.69            0.00      4501183.12   
9845    145   1767886.02     1767886.02            0.00            0.00   
10799   230  10000000.00    13774746.08      3774746.08            0.00   
2732      2    147141.81     1398839.54      1545981.34       221285.85   

       newbalanceDest  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
14402            0.00               0              0           0   
11624            0.00               0              0           0   
6422             0.00               0              0           0   
9427             0.00               0              0           0   
5126       4313939.72               0              0           0   
...               ...             ...            ...         ...   
9225             0.00               0              0           0   
13123      9127452.81               0              1           0   
9845             0.00               0              0           0   
10799            0.00               0              0           0   
2732         74144.04               0              0           0   

       type_PAYMENT  type_TRANSFER  
14402             0              1  
11624             0              1  
6422              1              0  
9427              0              1  
5126              0              1  
...             ...            ...  
9225              0              1  
13123             0              0  
9845              0              1  
10799             0              1  
2732              0              0  

[10950 rows x 11 columns]

In [12]:
# 1.RANDOM_CLASSIFIER USING GRIDSEARCH
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entrophy'],
            'max_features':['auto','sqrt','log2'],
            'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1')
grid.fit(x_train,y_train)

print(grid.best_params_)


Fitting 5 folds for each of 12 candidates, totalling 60 fits
{'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 10}


C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\ensemble\_forest.py", line 467, in fit
    for i, t in enumerate(trees)
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\joblib\parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:

In [13]:
#SAMPLE OF DATA FROM ORIGINAL DATASET
y_pred=grid.predict(x_test)


In [14]:
y_pred
pd.DataFrame(y_pred)

0
0     1
1     1
2     0
3     1
4     0
...  ..
5471  1
5472  0
5473  1
5474  0
5475  1

[5476 rows x 1 columns]

In [15]:
#EVALUTION METRICS IN CLASSIFICATION
from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(y_pred,y_test)
print( Fore.BLUE+"Random forest Confusion matrix:")
print(cm1)

Random forest Confusion matrix:
[[2722    6]
 [   0 2748]]


In [16]:
#CLASSIFICATION REPORT
from sklearn.metrics import classification_report
clf1=classification_report(y_pred,y_test)
print(Fore.RED + "Random forest:")
print(clf1)
print(cm1)

Random forest:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2728
           1       1.00      1.00      1.00      2748

    accuracy                           1.00      5476
   macro avg       1.00      1.00      1.00      5476
weighted avg       1.00      1.00      1.00      5476

[[2722    6]
 [   0 2748]]


#2.DECISION TREE CLASSIFICATION

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entrophy'],
            'max_features':['auto','sqrt','log2'],
            'splitter':['best','random']}
grid1=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid1.fit(x_train,y_train)

print(grid1.best_params_)


Fitting 5 folds for each of 12 candidates, totalling 60 fits
{'criterion': 'gini', 'max_features': 'auto', 'splitter': 'best'}


C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: '

In [18]:
y_pred1=grid1.predict(x_test)
y_pred1

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [19]:
from sklearn.metrics import confusion_matrix
cm2=confusion_matrix(y_pred1,y_test)
print("Decisiontree confusion matrix:")
print(cm2)

Decisiontree confusion matrix:
[[2713   15]
 [   9 2739]]


In [20]:
from sklearn.metrics import classification_report
clf3=classification_report(y_pred1,y_test)
print("Decisiontree:")
print(clf3)
print(cm2)

Decisiontree:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      2728
           1       0.99      1.00      1.00      2748

    accuracy                           1.00      5476
   macro avg       1.00      1.00      1.00      5476
weighted avg       1.00      1.00      1.00      5476

[[2713   15]
 [   9 2739]]


In [21]:
# 3.LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid={'solver':['newton_cg','lbfgs','liblinear','saga']}
            
grid2=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid2.fit(x_train,y_train)

print(grid2.best_params_)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
{'solver': 'liblinear'}


C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Yaazh\anaconda3\envs\ai\lib\site-packages\sklearn\linear_model\_logistic.py", line 436, in _check_sol

In [22]:
y_pred2=grid2.predict(x_test)
y_pred2

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix
cm4=confusion_matrix(y_pred2,y_test)
print("logistic:")
print(cm4)

logistic:
[[1678   34]
 [1044 2720]]


In [24]:
from sklearn.metrics import classification_report
clf4=classification_report(y_pred2,y_test)
print("logistic:")
print(clf4)
print(cm4)

logistic:
              precision    recall  f1-score   support

           0       0.62      0.98      0.76      1712
           1       0.99      0.72      0.83      3764

    accuracy                           0.80      5476
   macro avg       0.80      0.85      0.80      5476
weighted avg       0.87      0.80      0.81      5476

[[1678   34]
 [1044 2720]]


In [25]:
#4.KNEIGHBORS_CLASSIFICATION
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)
classifier.fit(x_train,y_train)



KNeighborsClassifier(n_neighbors=7)

In [26]:
y_pred3=classifier.predict(x_test)
y_pred3

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix
cm5=confusion_matrix(y_pred3,y_test)
print("KNeighbors confusion matrix:")
print(cm5)

KNeighbors confusion matrix:
[[2610   58]
 [ 112 2696]]


In [28]:
from sklearn.metrics import classification_report
clf5=classification_report(y_pred3,y_test)
print("KNeighbors classification Report:")
print(clf5)
print(cm5)

KNeighbors classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      2668
           1       0.98      0.96      0.97      2808

    accuracy                           0.97      5476
   macro avg       0.97      0.97      0.97      5476
weighted avg       0.97      0.97      0.97      5476

[[2610   58]
 [ 112 2696]]


In [29]:
#5.NAIVE_BAYES_CLASSIFICATION
from sklearn.naive_bayes import GaussianNB
classifier1=GaussianNB()
classifier1.fit(x_train,y_train)



GaussianNB()

In [30]:
y_pred4=classifier1.predict(x_test)

In [31]:
y_pred4

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [32]:
from sklearn.metrics import confusion_matrix
cm6=confusion_matrix(y_pred4,y_test)
print("NaiveBayes confusion matrix:")
print(cm6)

NaiveBayes confusion matrix:
[[2677  563]
 [  45 2191]]


In [33]:
from sklearn.metrics import classification_report
clf6=classification_report(y_pred4,y_test)
print( Fore.RED+"NaiveBayesclassifiction report")
print(clf6)
print(cm6)

NaiveBayesclassifiction report
              precision    recall  f1-score   support

           0       0.98      0.83      0.90      3240
           1       0.80      0.98      0.88      2236

    accuracy                           0.89      5476
   macro avg       0.89      0.90      0.89      5476
weighted avg       0.91      0.89      0.89      5476

[[2677  563]
 [  45 2191]]


In [34]:
#SUPPORT VECTOR CLASSIFIACATION
from sklearn.svm import SVC
classi=SVC()
classi.fit(x_train,y_train)

SVC()

In [35]:
y_pred6=classi.predict(x_test)

In [36]:
from sklearn.metrics import confusion_matrix
cm7=confusion_matrix(y_pred6,y_test)
print("SuportVectorConfusionMatrix:")
print(cm7)

SuportVectorConfusionMatrix:
[[2671  692]
 [  51 2062]]


In [37]:
from sklearn.metrics import classification_report
clf7=classification_report(y_pred6,y_test)
print("SuportVectorClassification report:")
print(clf7)
print(cm7)


SuportVectorClassification report:
              precision    recall  f1-score   support

           0       0.98      0.79      0.88      3363
           1       0.75      0.98      0.85      2113

    accuracy                           0.86      5476
   macro avg       0.86      0.89      0.86      5476
weighted avg       0.89      0.86      0.87      5476

[[2671  692]
 [  51 2062]]



     DEPOLYMENT 

In [38]:
import pickle
filename="finalized_model_RandomForestClassifier"
pickle.dump(grid1,open(filename,'wb'))

In [39]:
load_model=pickle.load(open(filename,'rb'))

In [ ]:
Trans_Type=int(input("TYPE:"))
Amount=int(input("AMOUNT:"))
OldBalance=int(input("OLD BALANCE:")) 
NewBalance=int(input("NEW BALANCE:"))
OldBalanceDest=int(input("OLDBALANCEDEST:"))
NewBalanceDest=int(input("NEW BALACE DEST:"))
IsFlaggedFraud=int(input("ISFLAGGEDFRAUD:"))
Type_Cash_Out=int(input("TYPECASHOUT 0 OR 1:"))
Type_Debit=int(input("TYPE_DEBIT 0 OR 1:"))
Type_Payment=int(input("TYPE_PAYMENT 0 OR 1:"))
Type_Transfer=int(input("TYPE_TRANSFER 0 OR 1:"))

In [ ]:
Future_Prediction=grid.predict([[Trans_Type,Amount,OldBalance,NewBalance,OldBalanceDest,NewBalanceDest,IsFlaggedFraud]])
print("Future_Prediction={}".format(Future_Prediction))
